OjelmoinninJatkokurssinLopputehtava/Controllers/HenkiloController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OhjelmoinninJatkokurssinLopputehtava.Models;

namespace OhjelmoinninJatkokurssinLopputehtava.Controllers
{
    public class HenkiloController : Controller
    {
        // GET: Henkilo
        public ActionResult Index()
        {
            ProjektitEntities entities = new ProjektitEntities();
            var model = entities.Henkilot.ToList();
            entities.Dispose();

            return View(model);
        }

        public ActionResult Projektitunnit(int henkilo_id)
        {   
            ProjektitEntities entities = new ProjektitEntities();
            var model = entities.Tunnit.Where(t => t.Henkilo_id == henkilo_id).ToList();

            //projektin nimi näkymää varten
            var nimi = (from hl in entities.Henkilot
                        where hl.Henkilo_id == henkilo_id
                        select (hl.Etunimi + " " + hl.Sukunimi)).ToList().FirstOrDefault();
            ViewBag.Henkilonimi = nimi;

            // nimilista näkymää varten
            Dictionary<int, string> names = new Dictionary<int, string>();
            var pr = entities.Projektit.ToList();
            foreach (var p in pr)
            {
                names.Add(p.Projekti_id, p.Nimi);
            }
            ViewBag.Projektilista = names;

            entities.Dispose();

            return View(model);
        }


    }
}

OjelmoinninJatkokurssinLopputehtava/Controllers/ProjektiController.cs
using OhjelmoinninJatkokurssinLopputehtava.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OhjelmoinninJatkokurssinLopputehtava.Controllers
{
    public class ProjektiController : Controller
    {
        // GET: Projekti
        public ActionResult Index()
        {
            var entities = new ProjektitEntities();
            var model = entities.Projektit.ToList();
            entities.Dispose();
            return View(model);
        }

        public ActionResult Henkilotunnit(int projekti_id)
        {
            ProjektitEntities entities = new ProjektitEntities();
            var model = entities.Tunnit.Where(t => t.Projekti_id == projekti_id).ToList();
            

            //projektin nimi näkymää varten
            var nimi = (from pr in entities.Projektit
                        where pr.Projekti_id == projekti_id
                        select pr.Nimi).ToList().FirstOrDefault();
            ViewBag.ProjektiNimi = nimi;

            // nimilista näkymää varten
            Dictionary<int, string> names = new Dictionary<int, string>();
            var ht = entities.Henkilot.ToList();
            foreach(var h in ht)
            {
                names.Add(h.Henkilo_id, h.Etunimi + " " + h.Sukunimi);
            }
            ViewBag.Nimilista = names;

            entities.Dispose();

            return View(model);
        }
    }
}

OjelmoinninJatkokurssinLopputehtava/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Sebastian Bojers' ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Ohjelmoinnin jatkokurssi", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Etusivu", "Index", "Home")</li>
                    <li>@Html.ActionLink("Henkilöt", "Index", "Henkilo")</li>
                    <li>@Html.ActionLink("Projektit", "Index", "Projekti")</li>
                </ul>
                <!--@Html.Partial("_LoginPartial")-->
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Sebastian Bojers' ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>